### ISSUE TITLE
Error with Fooman Speedster Advanced

### ISSUE THREAD

**Issue by Razorphyn** [yireo/Yireo_GoogleTagManager#1]
Hi,
when I run the theme optimization function, the page returns this error:

`Fatal error: Class 'Zend_Log' not found in app/code/community/Yireo/GoogleTagManager/Block/Default.php on line 52`

**Comment by yireo** [comment]
We've installed Fooman Speedster and our own GoogleTagManager extension as a test on 3 different websites (Magento 1.7, Magento 1.8 and Magento 1.9) and in our case, this installation does not cause any issues. Because our extension is very generic and its only particular thing is that it hooks into the event "core_block_abstract_to_html_after" event (which is complying to Magento standards), I trust that this issue is actually an error in the Fooman Speedster extension. Did you already report that issue to Fooman itself?

If you have a fix for this that can be incorporated in our extension, we are happy to accept your pull request. Hope to hear from you soon.
