### ISSUE TITLE
Comma in productName causes a new line in Google's Tag Assistant Chrome extension

### ISSUE THREAD

**Issue by Lex50** [yireo/Yireo_GoogleTagManager#103]
productName does not display correctly in Google's Tag Assistant Chrome extension, when a comma is present in the product name, e.g. "Chelsea, Tee".

<img width="1340" alt="Screenshot 2019-04-05 at 11 50 59" src="https://user-images.githubusercontent.com/768541/55623497-17104380-579b-11e9-8406-ca7eff240162.png">

**Comment by jissereitsma** [comment]
Is this a bug in our extension? The GTM standard is perfectly fine with having comma's in various values, including the product name. Also, the GTM console doesn't report any issues if a comma is used. It seems that you are making 2 mistakes: First of all, you are looking at a third party browser extension that is totally unrelated to this Magento extension. So you might want to report this to the creators of that browser extension. Second, you are reporting an issue in that browser extension, while the screenshot doesn't show any error there. Yes, the comma makes the JSON output to be spread across multiple lines, but there is no error reported by the tool. Feel free to discuss the relevance of formatting of JSON with commas with the browser extension developers. But because this seems not related to this Magento extension at all, I'm closing this issue.
