### ISSUE TITLE
Very slow when showing anchored categories with large quantity of products

### ISSUE THREAD

**Issue by kebian** [yireo/Yireo_GoogleTagManager#12]
Brilliant extension but...

I have a category here at http://www.rossmod.co.uk/brands/mcd-racing.html
This page will take up to 98 seconds to load if it's set as an anchor category and 2 seconds if not.  The profile shows that all the time is spent in this extension, with the main culprits being the following.

frontend/base/default/template/googletagmanager/category.phtml
frontend/base/default/template/googletagmanager/script.phtml

Disabling the extension altogether does indeed solve the load time.

**Comment by kebian** [comment]
Ok, the problem is in the category.phtml template.  Although there is a check there to stop adding products from the collection after the 3rd iteration, it's still the source of the slowdown.

I've tried changing the continue to a break but it made no noticeable speed difference.  I suspect the source of the problem is that the foreach call is triggering the select to get a record count, which is slow.

My knowledge of Magento is limited but I've tried several things.

I tried to limit the collection itself but that doesn't work since it limits what products are shown on the pages.  I thought about returning a cloned collection with a limit but Magento doesn't seem to implement the __clone operator in the collection class.

Then I thought about pulling the first 3 products by indexing the collection object like an array but the class doesn't seem to support that either.

In the end, I decided to comment out the section in category.phtml that adds the first 3 products.  Perhaps you can think of a better solution, but as I said my knowledge of Magento is quite limited.

**Comment by yireo** [comment]
Thanks for the feedback. We have done some testing of our own and can conclude that this problem that you describe does not occur in our testing environments with only our own Magento extensions plus the Magento core (and 50.000 SKUs). This shows that the issue is not simply due to our own extension, but due to something specific in your own Magento site (most likely third party extensions) plus our Yireo GoogleTagManager extension.

The only fix we can see for now is that the `continue` statement is wrong and it should be `break`. We will include this small bugfix in a new version shortly.

The problem of optimizing here is mainly that normally you can manipulate a collection before it is being loaded. The problem with this collection is that the collection is already loaded, and it is inserted into the GoogleTagManager extension "as is". If the collection is so large that it causes issues, the problem does not lie so much in the GTM extension itself, but more in the original loading of the collection. But why this occurs in your situation and not our own testing situations, is something that we can only troubleshoot by profiling your specific environment. If you want us to pick up on that via a custom project, let's get into contact (mail info@yireo.com).

We will add a new option "Load Products in Category" that allows you to disable the product loading without changing the code.
