### ISSUE TITLE
dataLayer checkout for Enhanced eCommerce

### ISSUE THREAD

**Issue by hans2103** [yireo/Yireo_GoogleTagManager#15]
The current dataLayer on the checkout page does not contain the correct structure for enhanced ecommerce.
https://developers.google.com/tag-manager/enhanced-ecommerce#purchases

please implement this. It will improve the data in Google Analytics

**Comment by yireo** [comment]
No pull request. Currently little time for more voluntary work :(

**Comment by yireo** [comment]
This is provided in a preliminary form now in the entire module. However to track specific links, those links still need to be modified in the PHTML templates that generates these links. This modification is not provided in this module, because this would require modification of 100s templates. Instead, documentation is provided on our site: https://www.yireo.com/software/magento-extensions/google-tag-manager
