### ISSUE TITLE
Regression due to product collection sort refactor

### ISSUE THREAD

**Issue by edannenberg** [yireo/Yireo_GoogleTagManager#28]
The changes introduced in https://github.com/yireo/Yireo_GoogleTagManager/commit/1cb9c5480a2ba935efc7570354c8931434ec25b0 and https://github.com/yireo/Yireo_GoogleTagManager/commit/4b64cbfd6fd06d2b8cdcce442240058086b0771d broke default sorting again for us. Although the changes use the "Magento way" to retrieve the sort attributes it also limits any customization by other means when you can't just mark another attribute via Magento backend for usage in product sort.

You are using the `$productListBlock` anyways to retrieve the product collection, why not use the getters provided by the block to retrieve the current sort attribute and order? #[KISS](https://en.wikipedia.org/wiki/KISS_principle) ;)

**Comment by jissereitsma** [comment]
I'm not sure if I follow. New attributes that are marked via the Magento backend for sorting, should be picked up by the call `Mage::getModel('catalog/config')->getAttributesUsedForSortBy()` which is actually used in the latest version. This would be the cleanest solution. Kissing or not.

Initially the only way of sorting things was to rely on the `$productListBlock` methods. Unfortunately this was not working for many people. I'm not sure why, because I've never seen such an environment and was never asked to spend (paid) time to dive into such an environment. Possibly this had to do with block caching of the `$productListBlock` or possibly with caching of subblocks. But simply because others had issues, I added these _improvements_.

It makes me a bit tired. I seem to be given evidence over-and-over again that things do not work as expected, but I'm missing the further prove of why it is not working. Because I can't spend voluntary time on the customization projects, I'm just going for an ugly approach instead: Add a switch option **Sorting method** which will default to the new method, but which will allow you to step back to the original block method (**Original block sorting**). This switch can only be removed then if enough evidence is gathered that one solution works for all cases. Let me know if that's ok with you.

I will now work on releasing version 1.3.23 to ship this system option.

**Comment by edannenberg** [comment]
> This would be the cleanest solution. Kissing or not.

I'd argue that the layer is too low, it just queries the db/attribute config and calls it a day. The previous approach allowed for full customization as it just mirrored what is actually used in the frontend. Much cleaner in my eyes.

Btw, the KISS reference wasn't meant to offend.

> Unfortunately this was not working for many people. I'm not sure why, because I've never seen such an environment and was never asked to spend (paid) time to dive into such an environment. Possibly this had to do with block caching of the $productListBlock or possibly with caching of subblocks.

Gotta say this sounds odd, they should have the exact same problems without this extension then? Maybe it's related to the insert method configuration option, IIRC I had to switch from observer to xml layout to avoid caching troubles.

> This switch can only be removed then if enough evidence is gathered that one solution works for all cases. Let me know if that's ok with you.

Sounds fine to me and should satisfy both camps. I wasn't aware that other people had issues with this, looked like an innocent refactor bug to me that could easily slip by.

**Comment by jissereitsma** [comment]
No offense taken, whatsoever - I was just trying to be strict and still mention that I was annoyed - not with you, but with the thing :)

Indeed it sounds really odd to me to have had the earlier issues - and me not being replicate things got things worse. Release is made anyway. If it does not work for you, let me know.

**Comment by edannenberg** [comment]
Ah, they joys of maintaining an open source repository, eh? I feel thy pain :p

Thanks for the quick fix! looks good to me

**Comment by edannenberg** [comment]
So sorry dude but it's not over yet, but I'm confident this will be the last time you have to hear about this. :p

I'm about to relaunch a shop when this previously unknown issue came up while testing. As it is both approaches break session parameter memoization for order and direction in the frontend. The reason again being that the product collection of the list block is loaded before the frontend sets the actual values that should be used, effectively ignoring them.

The only clean solution I see is to call `$productListBlock->toHtml();` before using the [collection](https://github.com/yireo/Yireo_GoogleTagManager/blob/master/source/app/code/community/Yireo/GoogleTagManager/Block/Category.php#L42). This will initialize everything correctly and not break frontend features. It also doesn't break everything that listens for `catalog_block_product_list_collection` observer event. Another short coming of both approaches currently.

I can shoot you a PR as I need this anyways, just wanted to hear your opinion first.

**Comment by edannenberg** [comment]
I guess a downside would be that the event is called twice per request. Maybe cloning the collection before loading it is the only valid approach, everything else will just f*ck with something in one way or the other.

**Comment by jissereitsma** [comment]
I'm not sure what this "session parameter memoization" is that is breaking, but I can safely say this all worked from the beginning with the Magento core and its default extensions, and it only breaks when there is non-default situation (i.e. with specific Magento extensions installed). I'm happy to keep this issue open, but somebody needs to invest time to see which exact Magento extensions (or which code changes to the code) also prevent the "session parameters" from working properly. As of yet, I need to stand down a bit on volunteering to troubleshoot these custom environments. I'm happy to assist though when this is replicated in a plain Magento environment with only the Yireo extension installed.

**Comment by edannenberg** [comment]
> I'm not sure what this "session parameter memoization" is that is breaking

Per default Magento will save the catalog sort order and direction in the `catalog/session` model, i.e. you select order by price in the frontend and then click some other category link and you should still order by price even though it is no longer present in the url params.

> but I can safely say this all worked from the beginning with the Magento core and its default extensions

I highly doubt that as it simply was not possible to work with the current approaches, once the googletagmanager blocks initialize the product collection all further attempts to modify the order/direction are ignored as that collection is then cached in the `productListBlock`.

> I'm happy to assist though when this is replicated in a plain Magento environment with only the Yireo extension installed.

I will try that tomorrrow, but I verified that things worked as expected again once I disabled this extension or after I added the above mentioned `$productListBlock->toHtml()` call.

**Comment by jissereitsma** [comment]
I did test this with both methods now available. The reason there came a URL method in the first place, is to have this problem (and a few others) solved was because of this kind of block caching. I've tested this again with both methods, but really could not confirm your statement that this problem of sorting parameters being lost, must exist with URL method as well. As of yet, I have your claim stating that this sorting of parameters should not work with URL methods, but in all my test cases it does. So I'm not sure where that claim comes from. Let's limit ourselves to only reporting confirmed issues that can be replicated all across the board.

I reinstated the original method (now dubbed as "block sorting") because I thought you mentioned that that previous method worked for you. Apparently, that previous method had a bug you did not catch yet. The new method (dubbed "URL sorting") was fixing that. As of yet, I have not seen other people reporting that this new method is not working for them, except for your claim which I can not reproduce.

The bug that I did reproduce was the bug that was there in the beginning, and which was the reason for a new URL method: Block caching being in the way. I have now applied a new fix that does NOT use the `toHtml()` method which would actually break lots of other things, but instead relies on the `$toolbar` block, because it seems that the sorting parameters are cached there. Again, this works for me, and let's limit ourselves to test cases that prove things to be not working and that can be replicated on different environments.

**Comment by edannenberg** [comment]
Sorry for not getting back to you sooner, was too tired yesterday for a detailed write up as the rabbit hole does still go a bit deeper. But we are getting to the bottom now. :p

>  I've tested this again with both methods, but really could not confirm your statement that this problem of sorting parameters being lost, must exist with URL method as well.

Correct, didn't look at the `getCurrentOrder`, etc helpers in `Category.php` which do take care of session params. However it was not handled by the "block sorting" method at the time.

> The bug that I did reproduce was the bug that was there in the beginning, and which was the reason for a new URL method: Block caching being in the way.

Not quite, the bug you fixed  today was simply session params not being handled by the "block sort" approach as the handling for that is in the toolbar block. As far as I can tell the "url sort" method should not resolve any issues related to block caching:
- per default Magento does NOT cache the `product_list` block, the block/collection is only cached per request, which is why it is crucial to set the correct order, etc before loading the collection the first time
- if you enable permanent block caching for `product_list` you effectively cache the complete product collection after it has loaded under the generated cache key, any attempts to modify the collection on a cache hit are effectively ignored for all further requests
- generating proper cache keys is up to the user/some caching extension
- if you generate proper cache keys for `product_list` there are no issues with both methods
- if you don't generate proper cache keys you will have weird issues depending on how bad your generated cache keys are. these issues will happen with both methods and without this extension as then a cached collection is used when it should not

I tested this yesterday extensively and discovered a 5-6 year old subtle bug in our full page cache extension which also enables block caching for `product_list`:
- when generating a cache key for `product_list` you also need to account for possible values in `catalog/session` related to order/direction/limit, in addition to url params

I have a feeling not many solutions will handle that correctly as it is quite subtle. But again, this has nothing to do with this extension, nor does the "url sorting" method resolve those issues.

> I have now applied a new fix that does NOT use the toHtml() method which would actually break lots of other things, but instead relies on the $toolbar block, because it seems that the sorting parameters are cached there.

Probably not intended then but currently you are using `toHtml()` in  [applyBlockSorting](https://github.com/yireo/Yireo_GoogleTagManager/blob/master/source/app/code/community/Yireo/GoogleTagManager/Block/Category.php#L71)? I'm not sure what breakage you are refering to though, worked fine for me. Of course using `toHtml()` would make all other code for setting order,limit etc redundant as it pretty much handles everything correctly. The only downside being that the `catalog_block_product_list_collection` event is called twice, but at least it would enable the first observer round to actually modify the collection, which is currently not possible due to this extension loading the collection before the event is fired. But I'd say let's leave that edge case until someone actually has issues with that.

Another issue with the "url sort" method is on search results, as it only relies on the [database](https://github.com/yireo/Yireo_GoogleTagManager/blob/master/source/app/code/community/Yireo/GoogleTagManager/Block/Category.php#L85) level for avail. sort attributes it currently does not sort by relevance, as that sort "attribute" is just injected by the search result block. A good example of why I think the "url sort" method is not the best approach. Another subtle bug I ran into: session params for order and direction (but not limit!) need to be ignored while being on search results, else you will end up ordering by what is set in the session as the `?order=relevance` url param is not in the url per default when you start a search.

I have tested everything pretty much to death now with the "block sorting" option enabled on vanilla and a highly optimized Magento with extensive block caching. IMHO the "url sorting" method should not be default, if not removed. It just replicates what happens in product_list/toolbar anyways while limiting any customization. Any block caching issues are not the fault of this extension and most likely related to wrong cache key implementations by the user or some other extension. The "block sort" method is upgrade safe (well, until Magento changes it's api that is :p) and enables full customization, this is what I consider clean. But in the end I don't really care too much as long as there is a working option.

I have refactored my PR from yesterday with your latest changes which also fixes the rest of the mentioned bugs, should be up in a minute. Sorry for the wall of text.
