### ISSUE TITLE
GTM Script is added again to the page

### ISSUE THREAD

**Issue by eliekstein** [yireo/Yireo_GoogleTagManager#35]
This code is causing the following script to be added to the page.
`<script async="" src="//www.googletagmanager.com/gtm.js?id=GTM-XXXXX"></script>`
In most cases this is already added by GTM's main tag provided to users, so this is causing for all events to be executed twice.

**Comment by jissereitsma** [comment]
Indeed our extension adds GTM to the page and it should do so, otherwise our extension does not work as described. But if you are using another mechanism to add also GTM to the page, then you (not the extension) are adding it twice to the page. Solution is to disable the other mechanism. This is not a bug in this extension, it's just the procedure we documented.
