### ISSUE TITLE
Category products sorting - FIXED

### ISSUE THREAD

**Issue by pfunkowski** [yireo/Yireo_GoogleTagManager#39]
Hi when I install our extension, products in category was poorly sorted.
in app/design/frontend/base/default/template/googletagmanager/category.phtm
replace line 13 to:
`$productCollection = $this->getLoadedProductCollection();`

ps. great extension, easy customize, but ... could you share some article about GTM configuration?

**Comment by jissereitsma** [comment]
As for the sorting issue, I'm not sure whether the code fix is actually an improvement to others. We have had long discussions about this kind of sorting issues before, and most likely the fix works for you because of some third party extensions, but it does not work in a generic Magento environment. Glad to hear that you found a work around though.

Please note that we are only supplying the technical implementation of GTM. It will require the help of a SEO guru on how to actually use the Google-based GTM panel, and I'm personally not a GTM guru. There are numerous guides that help with this though. But they don't deal with the technical installation of an extension in Magento so it is a bit where out help stops. We did not intend to be SEO experts by putting this module online, we simply thought the code could be improved.
