### ISSUE TITLE
Search Results Wrong Order When Doofinder Is Used

### ISSUE THREAD

**Issue by sprankhub** [yireo/Yireo_GoogleTagManager#49]
One of my customers uses your extension and the [Doofinder extension](https://github.com/doofinder/doofinder-magento) as well. Doofinder simply rewrites the `Mage_CatalogSearch_Model_Resource_Fulltext` class and fetches the results directly from Doofinder in the method `prepareResult`. This works flawlessly when `Yireo_GoogleTagManager` is not used. Once `Yireo_GoogleTagManager` is installed and active, the order of the search results is wrong. The search results are still "correct", but they are in the wrong order. As soon as `Yireo_GoogleTagManager` is disabled, the results are ordered correctly again. The issue is also solved if I remove the following lines from `Yireo_GoogleTagManager_Helper_Data`:

    $childScript .= $this->getSearchScript();
    $childScript .= $this->getTagScript();

As soon as one of these scripts is loaded, the results are in a wrong order. I tried to debug the issue as far as I could. But maybe this is a good point where you can have a look at the issue? Maybe you have any idea? You know much better what you are doing in your extension :-) Thanks!

**Comment by sprankhub** [comment]
Well... The fun thing is: Switching the insertion method to "observer" solves the issue. No idea why, but it seems to work.

**Comment by judaschwartz** [comment]
in `getTagScript()` and `getSearchScript()` functions i changed

        $productCollection = $tagBlock->getProductCollection();

to 

        $productCollection = $tagBlock->getLoadedProductCollection();

it seems to solve the sorting (am not sure if it breaks anything else)

**Comment by jissereitsma** [comment]
I have released a new version 1.4.0 which drastically changes things when dealing with the product collection. Instead of creating a new GTM block that tries to mimic the behaviour of the original `product_list` block, the new approach extends the original block using an observer. This allows for exactly the same `getLoadedProductCollection()` method to be used, after the original block has used it. Additionally, it seems to speed up things a bit. I'm closing this ticket for now, because it is related to removed code. If there are any new issues, do make sure to open a new ticket here.
