### ISSUE TITLE
$gtm gives wrong helper

### ISSUE THREAD

**Issue by razza12** [yireo/Yireo_GoogleTagManager#54]
Have been getting Fatal error: Call to undefined method Yireo_GoogleTagManager_Helper_Data::onClickProduct() after upgrading to the newest version. Should the reference in the template files reference
`<?php $gtm = Mage::helper('googletagmanager/script'); ?>` 
instead of
`<?php $gtm = Mage::helper('googletagmanager'); ?>` 
after the recent refactoring? This appears to get it working in my setup again.

**Comment by jissereitsma** [comment]
Because the helper is not injected directly into the PHTML templates anywhere, I assume that you refer to the comments. This is now updated. Indeed, if your own code uses a helper, this should be updated. https://github.com/yireo/Yireo_GoogleTagManager/commit/ddb608bb3dfcbeae488815b86d6eb91622a42a96
