### ISSUE TITLE
don't work properlu when use simbol order prefix

### ISSUE THREAD

**Issue by cheprasovstas** [yireo/Yireo_GoogleTagManager#71]
https://github.com/yireo/Yireo_GoogleTagManager/blob/17e8df16f7de337b48528bcb8239a4c6a6355e5c/source/app/code/community/Yireo/GoogleTagManager/Block/Order.php#L21

**Comment by cheprasovstas** [comment]
I use "PM000000001" order number format and it doesn't work

**Comment by jissereitsma** [comment]
Thanks. This is now fixed in the latest release. Please note that - because you are already focused on the exact line to be fixed - a simple PR was only steps away. I always encourage people to actually make PR, because committing contributions is more in the spirit of open source than just raising issues.
