### ISSUE TITLE
GDPR compliance

### ISSUE THREAD

**Issue by Razorphyn** [yireo/Yireo_GoogleTagManager#92]
Is it possible to provide a banner that asks for the explicit consent to collect this type of data (third-party service)and add the tag manager code only if allowed(decision stored in a cookie with selected life)?

**Comment by Razorphyn** [comment]
I have taken a quick look at the law and it looks like that you have to ask the permission only for sensible information, is it enough to edit the data layers, such as the removal of user id or email, enough to avoid the transmission of those information?

**Comment by jissereitsma** [comment]
I'm not sure if this belongs to the scope of this module. Another module would have the responsibility of adding a cookie banner. That cookie banner could then be integrated by someone with this module. Please note there will be many cookie banner modules available (and perhaps there are already modules that offer this behaviour) because there are many more cookies than just GTM cookies to take care off. I'm closing this issue for now, because I don't believe anyone is volunteering quickly for this feature in this extension. Feel free to re-open this, if you have started a PR on your side already.
